//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenBarter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForTrade
    {
        public int Id { get; set; }
        public int OwnerID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int MarketID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }
        public int CategoryID { get; set; }
        public string Tags { get; set; }
        public string Status { get; set; }
    }
}
