//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenBarter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int Id { get; set; }
        public string AboutMe { get; set; }
        public string EbayURL { get; set; }
        public string AmazonURL { get; set; }
        public string Email { get; set; }
        public string EtsyURL { get; set; }
        public string TwitterURL { get; set; }
        public string LinkedInURL { get; set; }
        public string WebsiteURL { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public int UserProfileID { get; set; }
    }
}
